var MSG = {
  catInOut:"INPUT / OUTPUT",
  catDigital:"Digital",
  catAnalog:"Analog",
  catSerial:"Serial",
  catSoftSerial:"Software Serial",
  catServo:"Servo",
  catDisplay:'Display',
  catSerialLCD:"Serial LCD",
  catSerialLCD_I2C:"Serial LCD I2C",
  catLCD:"LCD",
  catOLED:"OLED",
  catString:"String", 
  catDivers:"Various",
  title: "Code",
  blocks: "Blocks",
  linkTooltip: "Save and link to blocks.",
  runTooltip: "Run the program defined by the blocks in the workspace.",
  saveXMLTooltip:"Save XML",
  loadXMLTooltip:"Load XML",
  copycodeTooltip:"Copy Arduino code into clipboard",
  badCode: "Program error:\n%1",
  timeout: "Maximum execution iterations exceeded.",
  discard: "Delete all %1 blocks?",
  trashTooltip: "Discard all blocks.",
  catLogic: "Logic",
  catConversion:"Conversion",
  catAdvanced:"Advanced I/0",
  catLoops: "Loops",
  catMath: "Math",
  catText: "Text",
  catLists: "Lists",
  catColour: "Colour",
  catVariables: "Variables",
  catFunctions: "Functions",
  listVariable: "list",
  textVariable: "text",
  httpRequestError: "There was a problem with the request.",
  linkAlert: "Share your blocks with this link:\n\n%1",
  hashError: "Sorry, '%1' doesn't correspond with any saved program.",
  xmlError: "Could not load your saved file. Perhaps it was created with a different version of Blockly?",
  badXml: "Error parsing XML:\n%1\n\nSelect 'OK' to abandon your changes or 'Cancel' to further edit the XML.",
  warningBadBlock:"This block is not properly connected to other blocks.",
  warningPleaseFix:"Please fix the warning on this block."
  
};
