var MSG = {
    catInOut: "ENTRADA/SALIDA",
    catDigital: "Digital",
    catAnalog: "Analógico",
    catSerial: "Serial",
    catSoftSerial: "Software Serial",
    catServo: "Servo",
    catDisplay:'LCD Monitor',
    catSerialLCD: "LCD Serial",
    catSerialLCD_I2C: "Serial LCD I2C",
    catLCD: "LCD",
    catLCD_G: "LCD Monitor",
    catOLED:"OLED",
    catString: "Conjunto de caracteres",
    catDivers: "Varios",
    catConversion: "Conversión",
    catAdvanced: "I/0 Avanzado",
    title: "Código",
    blocks: "Bloques",
    linkTooltip: "Guarda conexión a los bloques.",
    runTooltip: "Ejecute el programa definido por los bloques en el área de trabajo.",
    saveXMLTooltip:"Salvar XML",
    loadXMLTooltip:"Carga XML",
    copycodeTooltip:"Copiar código Arduino en el portapapeles",
    badCode: "Error del programa:\n%1",
    timeout: "Se excedio el máximo de iteraciones ejecutadas permitidas.",
    trashTooltip: "Descartar todos los bloques.",
    catLogic: "Lógica",
    catLoops: "Secuencias",
    catMath: "Matemáticas",
    catText: "Texto",
    catLists: "Listas",
    catColour: "Color",
    catVariables: "Variables",
    catFunctions: "Funciones",
    listVariable: "lista",
    textVariable: "texto",
    httpRequestError: "Hubo un problema con la petición.",
    linkAlert: "Comparte tus bloques con este enlace:\n\n%1",
    hashError: "«%1» no corresponde con ningún programa guardado.",
    xmlError: "No se pudo cargar el archivo guardado.  ¿Quizá fue creado con otra versión de Blockly?",
    badXml: "Error de análisis XML:\n%1\n\nSelecciona OK para abandonar tus cambios o Cancelar para seguir editando el XML."
};
