var MSG = {
  catInOut:"Entrée / Sortie",
  catDigital:"Numérique",
  catAnalog:"Analogique",
  catSerial:"Série",
  catSoftSerial:"SoftwareSerial",
  catServo:"Servo",
  catDisplay:'Afficheurs',
  catSerialLCD:"LCD série",
  catSerialLCD_I2C:"LCD série I2C",
  catLCD:"LCD",
  catOLED:"OLED",
  catString:"Chaine de caractère",
  catDivers:"Divers",
  title: "Code",
  blocks: "Blocs",
  linkTooltip: "Sauvegarder et lier aux blocs.",
  runTooltip: "Lancer le programme défini par les blocs dans l’espace de travail.",
  saveXMLTooltip:"Enregistrer XML",
  loadXMLTooltip:"Charger XML",
  copycodeTooltip:"Copier le code Arduino dans le presse-papier",
  badCode: "Erreur du programme :\n%1",
  timeout: "Nombre maximum d’itérations d’exécution dépassé.",
  discard: "Supprimer tous les %1 blocs ?",
  trashTooltip: "Jeter tous les blocs.",
  catLogic: "Logique",
  catConversion:"Conversion",
  catAdvanced:"E/S Avancées",
  catSerial:"Serial",
  catLoops: "Boucles",
  catMath: "Math",
  catText: "Texte",
  catLists: "Listes",
  catColour: "Couleur",
  catVariables: "Variables",
  catFunctions: "Fonctions",
  listVariable: "liste",
  textVariable: "texte",
  httpRequestError: "Il y a eu un problème avec la demande.",
  linkAlert: "Partagez vos blocs grâce à ce lien:\n\n%1",
  hashError: "Désolé, '%1' ne correspond à aucun programme sauvegardé.",
  xmlError: "Impossible de charger le fichier de sauvegarde.  Peut être a t-il été créé avec une autre version de Blockly?",
  badXml: "Erreur d’analyse du XML :\n%1\n\nSélectionner 'OK' pour abandonner vos modifications ou 'Annuler' pour continuer à modifier le XML.",
  warningBadBlock:"Ce bloc est pas correctement connecté à d'autres blocs.",
  warningPleaseFix:"S'il vous plaît corriger l'avertissement sur ce bloc."
};
